-- MySQL Script generated by MySQL Workbench
-- 11/26/15 14:41:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistemashm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemashm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemashm` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sistemashm` ;

-- -----------------------------------------------------
-- Table `sistemashm`.`ln_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemashm`.`ln_clientes` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(80) NOT NULL COMMENT '',
  `dni` VARCHAR(45) NOT NULL COMMENT '',
  `direccion_principal` VARCHAR(128) NOT NULL COMMENT '',
  `tlf_pricipal` VARCHAR(15) NOT NULL COMMENT '',
  `tipo_dni` VARCHAR(1) NOT NULL COMMENT '',
  `fech_reg` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemashm`.`ln_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemashm`.`ln_users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `pass` VARCHAR(64) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `fech_reg` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `ln_clientes_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '',
  INDEX `fk_ln_users_ln_clientes1_idx` (`ln_clientes_id` ASC)  COMMENT '',
  CONSTRAINT `fk_ln_users_ln_clientes1`
    FOREIGN KEY (`ln_clientes_id`)
    REFERENCES `sistemashm`.`ln_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemashm`.`ln_actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemashm`.`ln_actividades` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descripcion` VARCHAR(45) NOT NULL COMMENT '',
  `fech_act` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `cant_hrs` FLOAT NOT NULL COMMENT '',
  `precio_unidad` FLOAT NOT NULL COMMENT '',
  `fech_reg` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `ln_clientes_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_ln_actividades_ln_clientes1_idx` (`ln_clientes_id` ASC)  COMMENT '',
  CONSTRAINT `fk_ln_actividades_ln_clientes1`
    FOREIGN KEY (`ln_clientes_id`)
    REFERENCES `sistemashm`.`ln_clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistemashm`.`ln_detalle_actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemashm`.`ln_detalle_actividades` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fech_detalle` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `descripcion` VARCHAR(160) NOT NULL COMMENT '',
  `viatico` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `fech_reg` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `ln_actividades_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_ln_detalle_actividades_ln_actividades1_idx` (`ln_actividades_id` ASC)  COMMENT '',
  CONSTRAINT `fk_ln_detalle_actividades_ln_actividades1`
    FOREIGN KEY (`ln_actividades_id`)
    REFERENCES `sistemashm`.`ln_actividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
