<div id="footer">
    <div class='alignleft'>
        <ul class="links" >
        	<li><a href='http://www.sistemashm.com/'>Sistemas HM</a> |</li>
        </ul>
    </div>
    <div class='alignright'>
    </div>
    <div class='alignleft clear'><a href=''>© 2015 - <?php echo date('Y');?> SistemasHM Team</a></div>
    <div class='alignright'><p><?php echo 'Tiempo: '.round((microtime(1)-START_TIME),4).' seg.'; echo ', Memoria Usada: '.number_format(memory_get_usage() / 1048576, 2).' MB';?></p></div>
</div>

